# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  alpha-nvim = {
    pname = "alpha-nvim";
    version = "234822140b265ec4ba3203e3e0be0e0bb826dff5";
    src = fetchFromGitHub {
      owner = "goolord";
      repo = "alpha-nvim";
      rev = "234822140b265ec4ba3203e3e0be0e0bb826dff5";
      fetchSubmodules = false;
      sha256 = "sha256-rXCibNJlNcF+p9PF7EoQM4/pnA1C+KGf7RrIyCY3OJY=";
    };
    date = "2023-09-14";
  };
  asyncrun-vim = {
    pname = "asyncrun-vim";
    version = "61cc3081963a12048e00e89f8cedc8bd1cb83b8c";
    src = fetchFromGitHub {
      owner = "skywind3000";
      repo = "asyncrun.vim";
      rev = "61cc3081963a12048e00e89f8cedc8bd1cb83b8c";
      fetchSubmodules = false;
      sha256 = "sha256-8xMsxQ/aVvTpI0R7gEty3e7+8v9R9YJEHNwbBcGcBtE=";
    };
    date = "2023-09-26";
  };
  asynctasks-vim = {
    pname = "asynctasks-vim";
    version = "7b77b195a4297d3e4c9dde01c20aa6be17e3fcf3";
    src = fetchFromGitHub {
      owner = "skywind3000";
      repo = "asynctasks.vim";
      rev = "7b77b195a4297d3e4c9dde01c20aa6be17e3fcf3";
      fetchSubmodules = false;
      sha256 = "sha256-FJjBAvjR89sOU+OKhL/ZwJ/AKmQjDdeir9K1G2aFbC8=";
    };
    date = "2023-09-21";
  };
  auto-dark-mode = {
    pname = "auto-dark-mode";
    version = "76e8d40d1e1544bae430f739d827391cbcb42fcc";
    src = fetchFromGitHub {
      owner = "f-person";
      repo = "auto-dark-mode.nvim";
      rev = "76e8d40d1e1544bae430f739d827391cbcb42fcc";
      fetchSubmodules = false;
      sha256 = "sha256-uJ4LxczgWl4aQCFuG4cR+2zwhNo7HB6R7ZPTdgjvyfY=";
    };
    date = "2023-09-23";
  };
  bufferline = {
    pname = "bufferline";
    version = "357cc8f8eeb64702e6fcf2995e3b9becee99a5d3";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "bufferline.nvim";
      rev = "357cc8f8eeb64702e6fcf2995e3b9becee99a5d3";
      fetchSubmodules = false;
      sha256 = "sha256-Soi4os5X8bdDcMY82lqI0nl3+eipvzLeJPhDX6FeKVk=";
    };
    date = "2023-10-02";
  };
  catppuccin = {
    pname = "catppuccin";
    version = "fc537040147f0374a22b88142a20eb6781141f0b";
    src = fetchFromGitHub {
      owner = "catppuccin";
      repo = "nvim";
      rev = "fc537040147f0374a22b88142a20eb6781141f0b";
      fetchSubmodules = false;
      sha256 = "sha256-NQA8tE+ZXy4TTPej6iOlP5cIHFnwf42tcBzitSI2sBM=";
    };
    date = "2023-10-05";
  };
  cmp-buffer = {
    pname = "cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      sha256 = "sha256-dG4U7MtnXThoa/PD+qFtCt76MQ14V1wX8GMYcvxEnbM=";
    };
    date = "2022-08-10";
  };
  cmp-cmdline = {
    pname = "cmp-cmdline";
    version = "8ee981b4a91f536f52add291594e89fb6645e451";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "8ee981b4a91f536f52add291594e89fb6645e451";
      fetchSubmodules = false;
      sha256 = "sha256-W8v/XhPjbvKSwCrfOAPihO2N9PEVnH5Cp/Fa25lNRw4=";
    };
    date = "2023-06-09";
  };
  cmp-git = {
    pname = "cmp-git";
    version = "f900a4cf117300fdc3ba31d26f8b6223ccd9c574";
    src = fetchFromGitHub {
      owner = "petertriho";
      repo = "cmp-git";
      rev = "f900a4cf117300fdc3ba31d26f8b6223ccd9c574";
      fetchSubmodules = false;
      sha256 = "sha256-McIYDGXu+tSaY/U6eu1XouSHto/mSpJ/i4Z4UKYa+mk=";
    };
    date = "2023-05-30";
  };
  cmp-nvim-lsp = {
    pname = "cmp-nvim-lsp";
    version = "44b16d11215dce86f253ce0c30949813c0a90765";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "44b16d11215dce86f253ce0c30949813c0a90765";
      fetchSubmodules = false;
      sha256 = "sha256-mU0soCz79erJXMMqD/FyrJZ0mu2n6fE0deymPzQlxts=";
    };
    date = "2023-06-23";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    };
    date = "2022-10-03";
  };
  cmp_luasnip = {
    pname = "cmp_luasnip";
    version = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
    src = fetchFromGitHub {
      owner = "saadparwaiz1";
      repo = "cmp_luasnip";
      rev = "05a9ab28b53f71d1aece421ef32fee2cb857a843";
      fetchSubmodules = false;
      sha256 = "sha256-nUJJl2zyK/oSwz5RzI9j3gf9zpDfCImCYbPbVsyXgz8=";
    };
    date = "2023-10-09";
  };
  color-picker = {
    pname = "color-picker";
    version = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
    src = fetchFromGitHub {
      owner = "ziontee113";
      repo = "color-picker.nvim";
      rev = "06cb5f853535dea529a523e9a0e8884cdf9eba4d";
      fetchSubmodules = false;
      sha256 = "sha256-a1hpKKvBG8ey/+gbfFEK8CPawEK9EdcQbnIfi7X0C9I=";
    };
    date = "2023-05-21";
  };
  comment = {
    pname = "comment";
    version = "0236521ea582747b58869cb72f70ccfa967d2e89";
    src = fetchFromGitHub {
      owner = "numtostr";
      repo = "comment.nvim";
      rev = "0236521ea582747b58869cb72f70ccfa967d2e89";
      fetchSubmodules = false;
      sha256 = "sha256-+dF1ZombrlO6nQggufSb0igXW5zwU++o0W/5ZA07cdc=";
    };
    date = "2023-08-07";
  };
  copilot-lua = {
    pname = "copilot-lua";
    version = "1a8032ae496916ccc7a7a52ee79194fbef29f462";
    src = fetchFromGitHub {
      owner = "zbirenbaum";
      repo = "copilot.lua";
      rev = "1a8032ae496916ccc7a7a52ee79194fbef29f462";
      fetchSubmodules = false;
      sha256 = "sha256-UqdPuLf8EPG3aGqj0yk9lTxkDUOdoEc9CRbINJZFcyg=";
    };
    date = "2023-09-21";
  };
  crates = {
    pname = "crates";
    version = "58bf989736765cae41fa5d0971027efeca033301";
    src = fetchFromGitHub {
      owner = "saecki";
      repo = "crates.nvim";
      rev = "58bf989736765cae41fa5d0971027efeca033301";
      fetchSubmodules = false;
      sha256 = "sha256-mM31uHkvnhEZ+3hLXVTjN9ZgBIzr3uBNQZ8drSqn3Rs=";
    };
    date = "2023-10-09";
  };
  diffview = {
    pname = "diffview";
    version = "d38c1b5266850f77f75e006bcc26213684e1e141";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "d38c1b5266850f77f75e006bcc26213684e1e141";
      fetchSubmodules = false;
      sha256 = "sha256-ZlEF5VZaE2LIfynaAzbcN9LP++0eAvyGzMF70Qds2K8=";
    };
    date = "2023-10-11";
  };
  dressing = {
    pname = "dressing";
    version = "1f2d1206a03bd3add8aedf6251e4534611de577f";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "1f2d1206a03bd3add8aedf6251e4534611de577f";
      fetchSubmodules = false;
      sha256 = "sha256-Tib3SZ88e15svL89me3tlTbUc8UcNY1jwLcr49FpRqc=";
    };
    date = "2023-10-10";
  };
  editorconfig = {
    pname = "editorconfig";
    version = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
    src = fetchFromGitHub {
      owner = "gpanders";
      repo = "editorconfig.nvim";
      rev = "5b9e303e1d6f7abfe616ce4cc8d3fffc554790bf";
      fetchSubmodules = false;
      sha256 = "sha256-pR57tITdVGF4luEmmRYv/XFb35E3KDfcgYRijkPAc+Y=";
    };
    date = "2023-01-10";
  };
  fidget = {
    pname = "fidget";
    version = "90c22e47be057562ee9566bad313ad42d622c1d3";
    src = fetchFromGitHub {
      owner = "j-hui";
      repo = "fidget.nvim";
      rev = "90c22e47be057562ee9566bad313ad42d622c1d3";
      fetchSubmodules = false;
      sha256 = "sha256-N3O/AvsD6Ckd62kDEN4z/K5A3SZNR15DnQeZhH6/Rr0=";
    };
    date = "2023-06-09";
  };
  flash = {
    pname = "flash";
    version = "6d76c5dee65181ab55cbdfb0760260e800d643f4";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "6d76c5dee65181ab55cbdfb0760260e800d643f4";
      fetchSubmodules = false;
      sha256 = "sha256-EUnmMrFWFhgDYZ1ohgjfskvq8ldp3XwVv67AUK6TrBU=";
    };
    date = "2023-10-05";
  };
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "43727c2ff84240e55d4069ec3e6158d74cb534b6";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "43727c2ff84240e55d4069ec3e6158d74cb534b6";
      fetchSubmodules = false;
      sha256 = "sha256-qKY2UEUToOLkAgTNvKb7SSstOX/KydkIUiqFZN8JU+o=";
    };
    date = "2023-10-01";
  };
  gitsigns = {
    pname = "gitsigns";
    version = "ff01d34daaed72f271a8ffa088a7e839a60c640f";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "ff01d34daaed72f271a8ffa088a7e839a60c640f";
      fetchSubmodules = false;
      sha256 = "sha256-J9j2OeoEvhl1V8Pzr7i/usVZ2LGI4emlpRGDX+uznjI=";
    };
    date = "2023-10-06";
  };
  glance = {
    pname = "glance";
    version = "8ed5cf3b3b1231ea696d88c9efd977027429d869";
    src = fetchFromGitHub {
      owner = "dnlhc";
      repo = "glance.nvim";
      rev = "8ed5cf3b3b1231ea696d88c9efd977027429d869";
      fetchSubmodules = false;
      sha256 = "sha256-oyfZUQiVGLSOkMnJF+V+IF4mGUiKbAN4YXq3gwxOVmQ=";
    };
    date = "2023-08-26";
  };
  go-nvim = {
    pname = "go-nvim";
    version = "cb8b5063732e00501050b2ced8e21a1e62cb3abd";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "go.nvim";
      rev = "cb8b5063732e00501050b2ced8e21a1e62cb3abd";
      fetchSubmodules = false;
      sha256 = "sha256-Lk6bYqrDMXmvrCi9JbKMUcuWYSXDL00TmWmFDmt3TPo=";
    };
    date = "2023-10-11";
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "5ad8dba19ce9b9fd8965598984dfdc9c119f97e4";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "5ad8dba19ce9b9fd8965598984dfdc9c119f97e4";
      fetchSubmodules = false;
      sha256 = "sha256-MF30YevxZUreW88RX/Tn9i/5GpqXqKcmH1tbDmsnoZY=";
    };
    date = "2023-08-15";
  };
  headlines = {
    pname = "headlines";
    version = "74a083a3c32a08be24f7dfcc6f448ecf47857f46";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "headlines.nvim";
      rev = "74a083a3c32a08be24f7dfcc6f448ecf47857f46";
      fetchSubmodules = false;
      sha256 = "sha256-35OgSoSf9sy5urwHZ3IxZPS/tWnUEhz7NZsClkqQZ6o=";
    };
    date = "2023-07-27";
  };
  indent-blankline = {
    pname = "indent-blankline";
    version = "1bee85e1789f61e5ee54e5a18f8fa193099dca99";
    src = fetchFromGitHub {
      owner = "lukas-reineke";
      repo = "indent-blankline.nvim";
      rev = "1bee85e1789f61e5ee54e5a18f8fa193099dca99";
      fetchSubmodules = false;
      sha256 = "sha256-rclAQpuk0+/xzhz8TwiWSyna5gQsgUuRTOEy68z3cBQ=";
    };
    date = "2023-10-11";
  };
  lazy = {
    pname = "lazy";
    version = "906ff8e569872d9081cfc9246d917011c22b5e61";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "906ff8e569872d9081cfc9246d917011c22b5e61";
      fetchSubmodules = false;
      sha256 = "sha256-PCQ05rxhiYwZOSmzDxsJNqWk9ao4m3sdtZh+UFuG8xg=";
    };
    date = "2023-10-11";
  };
  lsp-status = {
    pname = "lsp-status";
    version = "54f48eb5017632d81d0fd40112065f1d062d0629";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "lsp-status.nvim";
      rev = "54f48eb5017632d81d0fd40112065f1d062d0629";
      fetchSubmodules = false;
      sha256 = "sha256-gmLeVnDyL8Zf5ZG92tP3mb/LAt438BxFtAi/Xax2zLI=";
    };
    date = "2022-08-03";
  };
  lspkind = {
    pname = "lspkind";
    version = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
    src = fetchFromGitHub {
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "57610d5ab560c073c465d6faf0c19f200cb67e6e";
      fetchSubmodules = false;
      sha256 = "sha256-S+qZm51hw/cRujIfHV/1x1fYyCKI4XQ0utSL8uy4l6I=";
    };
    date = "2023-05-05";
  };
  ltex-extra = {
    pname = "ltex-extra";
    version = "9bed99b2b8488cc2daf66c76d2e0cf051ee80d13";
    src = fetchFromGitHub {
      owner = "barreiroleo";
      repo = "ltex-extra.nvim";
      rev = "9bed99b2b8488cc2daf66c76d2e0cf051ee80d13";
      fetchSubmodules = false;
      sha256 = "sha256-LzgAICiGuaHfYkQq7/4bRJ1M5KopFBcSTVTHrb3rm+w=";
    };
    date = "2023-07-28";
  };
  lualine = {
    pname = "lualine";
    version = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
      fetchSubmodules = false;
      sha256 = "sha256-v8finXk+sLNaFMA7pSHhEu0WF5mhPYWHEKhl0IKBv8c=";
    };
    date = "2023-08-03";
  };
  luasnip = {
    pname = "luasnip";
    version = "cdbf6f41381e5ee4810b4b09284b603d8f18365d";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "cdbf6f41381e5ee4810b4b09284b603d8f18365d";
      fetchSubmodules = false;
      sha256 = "sha256-qY0DnrpQf7SntjLsYPvFReGpEZqplvWVuJw/GbZwi/c=";
    };
    date = "2023-10-06";
  };
  markdown-preview = {
    pname = "markdown-preview";
    version = "02cc3874738bc0f86e4b91f09b8a0ac88aef8e96";
    src = fetchFromGitHub {
      owner = "iamcco";
      repo = "markdown-preview.nvim";
      rev = "02cc3874738bc0f86e4b91f09b8a0ac88aef8e96";
      fetchSubmodules = false;
      sha256 = "sha256-e1Buvu/lkEt9V5LVDFKWTasnSX6EdtRgWyVDZA8LpUE=";
    };
    "app/yarn.lock" = builtins.readFile ./markdown-preview-02cc3874738bc0f86e4b91f09b8a0ac88aef8e96/app/yarn.lock;
    date = "2022-05-13";
  };
  neoconf = {
    pname = "neoconf";
    version = "89fdbc02266d714413b805084a1b44d3cc8ce103";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neoconf.nvim";
      rev = "89fdbc02266d714413b805084a1b44d3cc8ce103";
      fetchSubmodules = false;
      sha256 = "sha256-Vry3HwpMeqN4XMS9o6/NX+Y0UpfAT4A84kaTLGeMVfo=";
    };
    date = "2023-10-10";
  };
  neodev = {
    pname = "neodev";
    version = "a4b6e7ca11ff5be2264d5c169fcedd97d8699ec4";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "a4b6e7ca11ff5be2264d5c169fcedd97d8699ec4";
      fetchSubmodules = false;
      sha256 = "sha256-sxn2e4GfsHK3s/cAvrAl0NHa5rNSneU/0qVrlKGt9Hw=";
    };
    date = "2023-10-11";
  };
  neogit = {
    pname = "neogit";
    version = "d3fbf8b48f4f8bc406eb23f8b06eb912776f8cb0";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "d3fbf8b48f4f8bc406eb23f8b06eb912776f8cb0";
      fetchSubmodules = false;
      sha256 = "sha256-ZkYqbBHl8Ir5+ASL1eobTHRNFm3H40Io4EoRYYmz/zM=";
    };
    date = "2023-10-11";
  };
  neorepl = {
    pname = "neorepl";
    version = "bc819bb42edca9c4a6b6e5d00f09f94a49c3b735";
    src = fetchFromGitHub {
      owner = "ii14";
      repo = "neorepl.nvim";
      rev = "bc819bb42edca9c4a6b6e5d00f09f94a49c3b735";
      fetchSubmodules = false;
      sha256 = "sha256-OkePRGuaLWE+NRdONAh14PijUF08HsYf9rvwi58fzRU=";
    };
    date = "2022-11-07";
  };
  neorg = {
    pname = "neorg";
    version = "7d507d4fdd1c4a3cb8a8299a469d22190ebaf7f0";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "7d507d4fdd1c4a3cb8a8299a469d22190ebaf7f0";
      fetchSubmodules = false;
      sha256 = "sha256-OS/IW9kS24UhjSsElYvhsGYVuznow226TM0g08W84ac=";
    };
    date = "2023-10-09";
  };
  neovim-session-manager = {
    pname = "neovim-session-manager";
    version = "68dde355a4304d83b40cf073f53915604bdd8e70";
    src = fetchFromGitHub {
      owner = "Shatur";
      repo = "neovim-session-manager";
      rev = "68dde355a4304d83b40cf073f53915604bdd8e70";
      fetchSubmodules = false;
      sha256 = "sha256-WOJQ6RIibOby+Pmzr6kQxcT2NCGrq1roWkh4QKJECks=";
    };
    date = "2023-10-09";
  };
  null-ls = {
    pname = "null-ls";
    version = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7";
    src = fetchFromGitHub {
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "0010ea927ab7c09ef0ce9bf28c2b573fc302f5a7";
      fetchSubmodules = false;
      sha256 = "sha256-cWA0rzkOp/ekVKaFee7iea1lhnqKtWUIU+fW5M950wI=";
    };
    date = "2023-08-11";
  };
  nvim-autopairs = {
    pname = "nvim-autopairs";
    version = "748e72c05495a3d30e88a6ef04b21697019a9aa9";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-autopairs";
      rev = "748e72c05495a3d30e88a6ef04b21697019a9aa9";
      fetchSubmodules = false;
      sha256 = "sha256-3LLDXLxE8ezfOaC2zinX+xxA0uootdnaC88pOIksDoY=";
    };
    date = "2023-10-07";
  };
  nvim-cmp = {
    pname = "nvim-cmp";
    version = "5dce1b778b85c717f6614e3f4da45e9f19f54435";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "5dce1b778b85c717f6614e3f4da45e9f19f54435";
      fetchSubmodules = false;
      sha256 = "sha256-WGck3By9GhnBUmzLGi2wnKjDreQx5kBOmHCbC5BZhfo=";
    };
    date = "2023-08-26";
  };
  nvim-colorizer-lua = {
    pname = "nvim-colorizer-lua";
    version = "dde3084106a70b9a79d48f426f6d6fec6fd203f7";
    src = fetchFromGitHub {
      owner = "nvchad";
      repo = "nvim-colorizer.lua";
      rev = "dde3084106a70b9a79d48f426f6d6fec6fd203f7";
      fetchSubmodules = false;
      sha256 = "sha256-hShQabr+UafsP+yicWkHycWLTbPhOpRpoa9oTMMVZ9o=";
    };
    date = "2023-02-27";
  };
  nvim-dap = {
    pname = "nvim-dap";
    version = "e79007c6d7a24db3ad19ea9196f1f0b2840e8ae7";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "e79007c6d7a24db3ad19ea9196f1f0b2840e8ae7";
      fetchSubmodules = false;
      sha256 = "sha256-9XJhAg91gjZlL4FFhRic6C+VuIWg3p+hMNqO2MEMayI=";
    };
    date = "2023-10-08";
  };
  nvim-dap-ui = {
    pname = "nvim-dap-ui";
    version = "34160a7ce6072ef332f350ae1d4a6a501daf0159";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "34160a7ce6072ef332f350ae1d4a6a501daf0159";
      fetchSubmodules = false;
      sha256 = "sha256-IdWPzLpNH0fkubELr2uTI7UnB0Yaf/zCkF8WUWBtyaM=";
    };
    date = "2023-09-10";
  };
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "57f1dbd0458dd84a286b27768c142e1567f3ce3b";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "57f1dbd0458dd84a286b27768c142e1567f3ce3b";
      fetchSubmodules = false;
      sha256 = "sha256-yzMRudA8Wag881ewzw82uXPzHoxaB6kAapPElKN6G6E=";
    };
    date = "2023-05-25";
  };
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "2b361e043810d5587d9af0787f8ce40da92ec5e9";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "2b361e043810d5587d9af0787f8ce40da92ec5e9";
      fetchSubmodules = false;
      sha256 = "sha256-i3lDsFwoMddpN1I4t3Fj+Dthyxq7twCgpYuNtlvfI5Y=";
    };
    date = "2023-10-06";
  };
  nvim-navic = {
    pname = "nvim-navic";
    version = "0ffa7ffe6588f3417e680439872f5049e38a24db";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "0ffa7ffe6588f3417e680439872f5049e38a24db";
      fetchSubmodules = false;
      sha256 = "sha256-X4CFFihI5PFIiHlwQt6VoUIxhm5oBuUvIQxCo9k7zRE=";
    };
    date = "2023-09-18";
  };
  nvim-notify = {
    pname = "nvim-notify";
    version = "e4a2022f4fec2d5ebc79afa612f96d8b11c627b3";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-notify";
      rev = "e4a2022f4fec2d5ebc79afa612f96d8b11c627b3";
      fetchSubmodules = false;
      sha256 = "sha256-1tWvzE4x1lgldg6vAHCQy9XDMcxJ6G9bZPSG1pEn+qg=";
    };
    date = "2023-09-28";
  };
  nvim-spectre = {
    pname = "nvim-spectre";
    version = "696cff781a4a7ecc91549736835e2acbd00fe859";
    src = fetchFromGitHub {
      owner = "nvim-pack";
      repo = "nvim-spectre";
      rev = "696cff781a4a7ecc91549736835e2acbd00fe859";
      fetchSubmodules = false;
      sha256 = "sha256-fvNJQTVgy7UA7VM1gnPcsDpU4QpFpzQ8sMmJ8eg0dSs=";
    };
    date = "2023-10-10";
  };
  nvim-surround = {
    pname = "nvim-surround";
    version = "1c2ef599abeeb98e40706830bcd27e90e259367a";
    src = fetchFromGitHub {
      owner = "kylechui";
      repo = "nvim-surround";
      rev = "1c2ef599abeeb98e40706830bcd27e90e259367a";
      fetchSubmodules = false;
      sha256 = "sha256-mc3PI2DwcSVe6eWjQzhh69+4Cv0m23puZ9oZbTFIQRo=";
    };
    date = "2023-08-17";
  };
  nvim-tree-lua = {
    pname = "nvim-tree-lua";
    version = "53b0bcaadaffb505acff230578b56a86ec1ab38a";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-tree.lua";
      rev = "53b0bcaadaffb505acff230578b56a86ec1ab38a";
      fetchSubmodules = false;
      sha256 = "sha256-8/JxdIY4v4kf24wLA8b2LE1HUD4gYpVEGJrZq7da7Nw=";
    };
    date = "2023-10-08";
  };
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "e5198778dbefa14823099dd6d8fba3819a5e7b8a";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "e5198778dbefa14823099dd6d8fba3819a5e7b8a";
      fetchSubmodules = false;
      sha256 = "sha256-1jwypf1tkqOqatQPVWg0UHpHnfEJ0hGDMiU6Yz1hweE=";
    };
    date = "2023-10-11";
  };
  nvim-treesitter-context = {
    pname = "nvim-treesitter-context";
    version = "4cf64264c049c55f256550ad247b606f3e53bc77";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-context";
      rev = "4cf64264c049c55f256550ad247b606f3e53bc77";
      fetchSubmodules = false;
      sha256 = "sha256-gtMkbCEMWjLDuP2SEs7LNSEHKA+gKRMUNCLs0bm5pt4=";
    };
    date = "2023-10-10";
  };
  nvim-treesitter-textobjects = {
    pname = "nvim-treesitter-textobjects";
    version = "76c7a89b41de77a4f83fb77fa072c5ad7605fe3b";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter-textobjects";
      rev = "76c7a89b41de77a4f83fb77fa072c5ad7605fe3b";
      fetchSubmodules = false;
      sha256 = "sha256-dYOavIV2w8LEUoWoYbi1CanGie0aBBG3ra6fM8fvaBA=";
    };
    date = "2023-10-07";
  };
  nvim-ts-autotag = {
    pname = "nvim-ts-autotag";
    version = "6be1192965df35f94b8ea6d323354f7dc7a557e4";
    src = fetchFromGitHub {
      owner = "windwp";
      repo = "nvim-ts-autotag";
      rev = "6be1192965df35f94b8ea6d323354f7dc7a557e4";
      fetchSubmodules = false;
      sha256 = "sha256-4qTtXYA5HyG1sADV0wsiccO/G89qEoYPmlg8tTx7h8g=";
    };
    date = "2023-06-16";
  };
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "a1e6268779411048a87f767a27380089362a0ce2";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "a1e6268779411048a87f767a27380089362a0ce2";
      fetchSubmodules = false;
      sha256 = "sha256-V1LFzoLngrWMJNPqcks/966PVHS3zYIhFyHmn3xMMQU=";
    };
    date = "2023-10-09";
  };
  octo = {
    pname = "octo";
    version = "15e1c949bdc6f77b1296977a6a7dde5d06c6c004";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "15e1c949bdc6f77b1296977a6a7dde5d06c6c004";
      fetchSubmodules = false;
      sha256 = "sha256-hiJKc8fXAM8MQDx6uR5FCL1alpHcV+G3HYIX183mfjw=";
    };
    date = "2023-10-09";
  };
  playground = {
    pname = "playground";
    version = "ba48c6a62a280eefb7c85725b0915e021a1a0749";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "ba48c6a62a280eefb7c85725b0915e021a1a0749";
      fetchSubmodules = false;
      sha256 = "sha256-gOQr61Y3bVa6EAb0P924X9SJmg9lOmGiLcFTMdgu8u0=";
    };
    date = "2023-09-15";
  };
  plenary = {
    pname = "plenary";
    version = "50012918b2fc8357b87cff2a7f7f0446e47da174";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "50012918b2fc8357b87cff2a7f7f0446e47da174";
      fetchSubmodules = false;
      sha256 = "sha256-zR44d9MowLG1lIbvrRaFTpO/HXKKrO6lbtZfvvTdx+o=";
    };
    date = "2023-10-11";
  };
  presence = {
    pname = "presence";
    version = "87c857a56b7703f976d3a5ef15967d80508df6e6";
    src = fetchFromGitHub {
      owner = "andweeb";
      repo = "presence.nvim";
      rev = "87c857a56b7703f976d3a5ef15967d80508df6e6";
      fetchSubmodules = false;
      sha256 = "sha256-ZpsunLsn//zYgUtmAm5FqKVueVd/Pa1r55ZDqxCimBk=";
    };
    date = "2023-01-29";
  };
  py_lsp = {
    pname = "py_lsp";
    version = "5b2bd6433a2dbab76d54d58ccc1d1e89b220091c";
    src = fetchFromGitHub {
      owner = "hallerpatrick";
      repo = "py_lsp.nvim";
      rev = "5b2bd6433a2dbab76d54d58ccc1d1e89b220091c";
      fetchSubmodules = false;
      sha256 = "sha256-YOYrumIYlWcZBL1LSeBWseb/0G4n8obcll6wPwaXqpM=";
    };
    date = "2023-02-28";
  };
  rainbow-delimiters = {
    pname = "rainbow-delimiters";
    version = "652345bd1aa333f60c9cbb1259f77155786e5514";
    src = fetchFromGitHub {
      owner = "hiphish";
      repo = "rainbow-delimiters.nvim";
      rev = "652345bd1aa333f60c9cbb1259f77155786e5514";
      fetchSubmodules = false;
      sha256 = "sha256-2WeOiyVxdUzMF5WUJttbElZ/Q2A9jbKy3buZI+3BgX8=";
    };
    date = "2023-10-03";
  };
  rust-tools = {
    pname = "rust-tools";
    version = "0cc8adab23117783a0292a0c8a2fbed1005dc645";
    src = fetchFromGitHub {
      owner = "simrat39";
      repo = "rust-tools.nvim";
      rev = "0cc8adab23117783a0292a0c8a2fbed1005dc645";
      fetchSubmodules = false;
      sha256 = "sha256-jtfyDxifchznUupLSao6nmpVqaX1yO0xN+NhqS9fgxg=";
    };
    date = "2023-07-10";
  };
  schemastore = {
    pname = "schemastore";
    version = "854b38820036d81c5e6af1cae8797776ae5df56a";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "schemastore.nvim";
      rev = "854b38820036d81c5e6af1cae8797776ae5df56a";
      fetchSubmodules = false;
      sha256 = "sha256-wti1b9/xM0LZ465v5pNKjrqPDnPtcAfTDfawmGwctRU=";
    };
    date = "2023-10-10";
  };
  tagalong-vim = {
    pname = "tagalong-vim";
    version = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
    src = fetchFromGitHub {
      owner = "AndrewRadev";
      repo = "tagalong.vim";
      rev = "5a2bbf2b1d5b657685a49d48d98a4aa921c1fde3";
      fetchSubmodules = false;
      sha256 = "sha256-zTdq7hg+tPTy803o+f3gIzb7TCw4KRgKAaLf7bBC1A4=";
    };
    date = "2023-09-07";
  };
  telescope = {
    pname = "telescope";
    version = "74ce793a60759e3db0d265174f137fb627430355";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "74ce793a60759e3db0d265174f137fb627430355";
      fetchSubmodules = false;
      sha256 = "sha256-RN1J2va4E/HBfaZ1qVvohJvyR4wYhylOqfJ65E8Cm9Q=";
    };
    date = "2023-10-11";
  };
  telescope-asynctasks = {
    pname = "telescope-asynctasks";
    version = "065300fb0a8ba6a1c81991da1873c73e136dcdc0";
    src = fetchFromGitHub {
      owner = "GustavoKatel";
      repo = "telescope-asynctasks.nvim";
      rev = "065300fb0a8ba6a1c81991da1873c73e136dcdc0";
      fetchSubmodules = false;
      sha256 = "sha256-50HiNqIeaBz1koWwNpLSa8vd+JTVALbafcufVn+S8hw=";
    };
    date = "2022-04-09";
  };
  telescope-file-browser = {
    pname = "telescope-file-browser";
    version = "6e51d0cd6447cf2525412220ff0a2885eef9039c";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-file-browser.nvim";
      rev = "6e51d0cd6447cf2525412220ff0a2885eef9039c";
      fetchSubmodules = false;
      sha256 = "sha256-OMUsmrn4A351p95KXHxW4B8etRuKnpHk9tJ2tQUXXc8=";
    };
    date = "2023-09-23";
  };
  telescope-fzf-native = {
    pname = "telescope-fzf-native";
    version = "6c921ca12321edaa773e324ef64ea301a1d0da62";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "6c921ca12321edaa773e324ef64ea301a1d0da62";
      fetchSubmodules = false;
      sha256 = "sha256-Hob1x/jwQYfphYGWQ/i44NVyCM+WFT5/4+J5J4/tLYA=";
    };
    date = "2023-09-10";
  };
  telescope-project = {
    pname = "telescope-project";
    version = "7c64b181dd4e72deddcf6f319e3bf1e95b2a2f30";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-project.nvim";
      rev = "7c64b181dd4e72deddcf6f319e3bf1e95b2a2f30";
      fetchSubmodules = false;
      sha256 = "sha256-H6lrPjpOUVleKHB0ziI+6dthg9ymitHhEWtcgYJTrKo=";
    };
    date = "2023-04-27";
  };
  telescope-ui-select = {
    pname = "telescope-ui-select";
    version = "b0015e6e4b46a64192c64b68dec9a9ac5a4e5690";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-ui-select.nvim";
      rev = "b0015e6e4b46a64192c64b68dec9a9ac5a4e5690";
      fetchSubmodules = false;
      sha256 = "sha256-4r3tTrdEfscG/llA//Q4FwbgB7I0+nggAwe1Z1gSDOU=";
    };
    date = "2023-10-11";
  };
  todo-comments = {
    pname = "todo-comments";
    version = "3094ead8edfa9040de2421deddec55d3762f64d1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "todo-comments.nvim";
      rev = "3094ead8edfa9040de2421deddec55d3762f64d1";
      fetchSubmodules = false;
      sha256 = "sha256-Qm8AJ8omU5eCfjLt91DVxLS0R3QHbfW55ZTegB1JvWI=";
    };
    date = "2023-07-28";
  };
  toggleterm = {
    pname = "toggleterm";
    version = "c80844fd52ba76f48fabf83e2b9f9b93273f418d";
    src = fetchFromGitHub {
      owner = "akinsho";
      repo = "toggleterm.nvim";
      rev = "c80844fd52ba76f48fabf83e2b9f9b93273f418d";
      fetchSubmodules = false;
      sha256 = "sha256-y+xMqHUJEBvZuE2+JRlfqZX9enWV0+qyTzuwU9PAK6c=";
    };
    date = "2023-10-02";
  };
  trouble = {
    pname = "trouble";
    version = "02219b557d4726a789be58c5d6bd6e139c46a9fe";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "02219b557d4726a789be58c5d6bd6e139c46a9fe";
      fetchSubmodules = false;
      sha256 = "sha256-HriW8D9qgatZda3NAb8uZXUAqe15/4LnJ8jPsrK/fks=";
    };
    date = "2023-10-10";
  };
  true-zen = {
    pname = "true-zen";
    version = "2b9e210e0d1a735e1fa85ec22190115dffd963aa";
    src = fetchFromGitHub {
      owner = "pocco81";
      repo = "true-zen.nvim";
      rev = "2b9e210e0d1a735e1fa85ec22190115dffd963aa";
      fetchSubmodules = false;
      sha256 = "sha256-euaxTWS98i14wvuKrFvdCRigsKqrSUwZpMEmYtUBBss=";
    };
    date = "2023-06-09";
  };
  typescript-tools = {
    pname = "typescript-tools";
    version = "ebddb35900bbf5fa41fffa0463b676bf08e474e6";
    src = fetchFromGitHub {
      owner = "pmizio";
      repo = "typescript-tools.nvim";
      rev = "ebddb35900bbf5fa41fffa0463b676bf08e474e6";
      fetchSubmodules = false;
      sha256 = "sha256-VC1LAj7cZaidkwBVBNmrlfzOgk+sc78ozBCERyOs144=";
    };
    date = "2023-10-04";
  };
  vim-dadbod = {
    pname = "vim-dadbod";
    version = "ee7e3bb5377d43cb31a101718dd0cfc09bb87d4b";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-dadbod";
      rev = "ee7e3bb5377d43cb31a101718dd0cfc09bb87d4b";
      fetchSubmodules = false;
      sha256 = "sha256-NdCjKsAQqFfRMFTe7u4NIGMtXXn/BAuSVVpdCuZyA84=";
    };
    date = "2023-10-06";
  };
  vim-dadbod-completion = {
    pname = "vim-dadbod-completion";
    version = "fc7321a17f4c55db11fae89a884ddf4724020bae";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-completion";
      rev = "fc7321a17f4c55db11fae89a884ddf4724020bae";
      fetchSubmodules = false;
      sha256 = "sha256-HMP+YBO0c1OXkn1na7rtg/Sf/pBec+3HOkQx+j/qfvg=";
    };
    date = "2023-04-25";
  };
  vim-dadbod-ui = {
    pname = "vim-dadbod-ui";
    version = "95fd22469507e86b78aa55d868c14108adee2881";
    src = fetchFromGitHub {
      owner = "kristijanhusak";
      repo = "vim-dadbod-ui";
      rev = "95fd22469507e86b78aa55d868c14108adee2881";
      fetchSubmodules = false;
      sha256 = "sha256-FJPZWqqZQJBYMXi/a0QgB2RZDkSr10Rj7kPmYODHKxE=";
    };
    date = "2023-09-29";
  };
  vim-fugitive = {
    pname = "vim-fugitive";
    version = "cbe9dfa162c178946afa689dd3f42d4ea8bf89c1";
    src = fetchFromGitHub {
      owner = "tpope";
      repo = "vim-fugitive";
      rev = "cbe9dfa162c178946afa689dd3f42d4ea8bf89c1";
      fetchSubmodules = false;
      sha256 = "sha256-poNiZqRMuw2+xlPsY8BIA3OCjRCpbh7uAyaWmlgPCUs=";
    };
    date = "2023-10-09";
  };
  vim-gnupg = {
    pname = "vim-gnupg";
    version = "f9b608f29003dfde6450931dc0f495a912973a88";
    src = fetchFromGitHub {
      owner = "jamessan";
      repo = "vim-gnupg";
      rev = "f9b608f29003dfde6450931dc0f495a912973a88";
      fetchSubmodules = false;
      sha256 = "sha256-B6hSEeNjJdDUDjM0DlmAxc3zRRcJz91//GPk6rCWn6I=";
    };
    date = "2022-05-18";
  };
  vim-helm = {
    pname = "vim-helm";
    version = "c2e7b85711d410e1d73e64eb5df7b70b1c4c10eb";
    src = fetchFromGitHub {
      owner = "towolf";
      repo = "vim-helm";
      rev = "c2e7b85711d410e1d73e64eb5df7b70b1c4c10eb";
      fetchSubmodules = false;
      sha256 = "sha256-NQXmIcDnUqbeiNX0QqvQbLGmONuC8HGFlfsBHBXWEc4=";
    };
    date = "2022-08-22";
  };
  vim-just = {
    pname = "vim-just";
    version = "b2113d846c1f5a400ac9c2f5ef762de8f99dc745";
    src = fetchFromGitHub {
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "b2113d846c1f5a400ac9c2f5ef762de8f99dc745";
      fetchSubmodules = false;
      sha256 = "sha256-G/kKV9xF+s3RqFYuQtmkXL1pAZfCd9k7a37hSkHv2JI=";
    };
    date = "2023-10-06";
  };
  vim-table-mode = {
    pname = "vim-table-mode";
    version = "9555a3e6e5bcf285ec181b7fc983eea90500feb4";
    src = fetchFromGitHub {
      owner = "dhruvasagar";
      repo = "vim-table-mode";
      rev = "9555a3e6e5bcf285ec181b7fc983eea90500feb4";
      fetchSubmodules = false;
      sha256 = "sha256-upjy6O1v7Sev5KwPvlia/bvAKDdH0a7eauQTOCCa+F8=";
    };
    date = "2022-10-20";
  };
  which-key = {
    pname = "which-key";
    version = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "7ccf476ebe0445a741b64e36c78a682c1c6118b7";
      fetchSubmodules = false;
      sha256 = "sha256-B1+EHd2eH/EbD5Kip9PfhdPyyGfIkD6rsx0Z3rXvb5w=";
    };
    date = "2023-07-28";
  };
}
